sudo: required
install:
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $ALPINE_USER .travis/build-pkgs
  chmod +x scripts/*.sh
  alpine_run $ALPINE_USER apk update
  alpine_run $ALPINE_USER apk add alpine-base linux-firmware linux-grsec xtables-addons-grsec
  alpine_run $ALPINE_USER scripts/mkimage.sh --platform rpi --arch armhf
notifications:
  email: false
