sudo: required
install:
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $ALPINE_USER .travis/build-pkgs
  alpine_run $ALPINE_USER scripts/bootstrap.sh aarch64
  alpine_run $ALPINE_USER scripts/mkimage.sh --platform rpi --arch armhf
notifications:
  email: false
